### PR TITLE
fix: deprecate ts_utils get_node_text #88

### PR DESCRIPTION
**Pull request by danymat**
This PR tries to fix the annoying deprecation. It should not break any workflow.
I keep the PR open waiting for feedback, and I merge if everything is okay.

Thanks for the patience !

### CODE REVIEW

**Comment by bryant-the-coder** [comment]
@danymat tested and showed no errors

**Comment by max397574** [comment]
@danymat I think this shouldn't work

**Comment by danymat** [comment]
Hmm in this case it works, but I will make sure to plan for every probable issue. Feel free to make a PR if you want to be quicker than me

**Comment by max397574** [comment]
just add `vim.split` like I did in my pr

**Pull request merged**
