### PR TITLE
Add annotation type autodetection

### PR DESCRIPTION
**Pull request by barakmich**
Creates a new generate() type, `any`, which contextually adds an annotation by whichever matching type is first found in the tree around the cursor.

So, if your cursor is in a function, it will annotate the function, if in a class or struct definition, it'll annotate that, etc.

This allows for a single keybind, with ```require('neogen').generate({ type = 'any' })``` that works in each scenario.

I'm happy to add some documentation, but wanted to open the PR first to see if it'd be useful :)

### CODE REVIEW

**Comment by danymat** [comment]
(Related: #30)

Hello ! Thanks for the PR ! I will take a look asap, and test it out. If I find it okay, we all have to create documentation to expose this new feature

**Comment by danymat** [comment]
Hello again, can you add some documentation on important portions of the code ?

**Comment by kdurant** [comment]
I want this feature.

**Comment by danymat** [comment]
Hello everyone, is this feature still wanted ?

**Comment by ssiyad** [comment]
> Hello everyone, is this feature still wanted ?

Yes, please

**Comment by ssiyad** [comment]
@danymat I opened another PR (#116) in which I tried to
- Add some comments
- Add `any` to help (`neogen.txt`)
- Clean up code a bit
- Shared table for types storage

**Comment by danymat** [comment]
Favored #116 so this feature can be moved forward.
Anyways, thanks @barakmich for your contribution as you were the foundations of the feature!

**Pull request closed without merging**
