### PR TITLE
Added Python "Yields:" support for Google-style docstrings

### PR DESCRIPTION
**Pull request by ColinKennedy**
From Google's style documentation: https://google.github.io/styleguide/pyguide.html#294-decision

An example is also available [in Sphinx-napoleon's documentation, here](https://sphinxcontrib-napoleon.readthedocs.io/en/latest/example_google.html)

In short

- If `yield` is present in a Python function, it's actually a generator
- If it's a generator, `Returns:` should be replaced with `Yields:`

## Demonstration
https://github.com/danymat/neogen/assets/10103049/af9fb168-ef18-442a-97ff-eb0d70f9a3cf

Only added for Google-style docstrings but could be added to other styles probably pretty easily

### CODE REVIEW

**Comment by danymat** [comment]
Hello, I tried to merge previous integrations with this feature. Can you provide a check and verify that everything is working ?

**Comment by danymat** [comment]
Yes that's why, my fear is that the throw statement and return one are conflicting with each other

**Comment by ColinKennedy** [comment]
Confirmed it was not working based on the latest main. It should be working now though

https://github.com/danymat/neogen/assets/10103049/14eb5011-5701-4230-82a4-74cee955b45b

A simple demo of functions that contain return, return and yield, and a bare return. The output is correct in these cases though more exhaustive testing might be needed as unittests.

**Comment by ColinKennedy** [comment]
Confirmed it was not working based on the latest main. It should be working now though

https://github.com/danymat/neogen/assets/10103049/14eb5011-5701-4230-82a4-74cee955b45b

A simple demo of functions that contain return, return and yield, and a bare return. The output is correct in these cases though more exhaustive testing might be needed as unittests.

**Comment by danymat** [comment]
Nice, tested and it seems to work.
Next step for me is to make unit tests for better PRs

**Pull request merged**
